version: "3.8"

services:
  nginx:
    image: ${USERNAME}/${DOCKER_IMAGE}:${IMAGE_TAG}
    ports:
        - "8080:80"
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
